import { NetworkConfig } from './web3-types';

export const supportedNetworks: NetworkConfig[] = [
  {
    chainId: 1,
    name: 'Ethereum Mainnet',
    rpcUrl: 'https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID', // Replace with your Infura Project ID
    blockExplorer: 'https://etherscan.io',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 11155111,
    name: 'Sepolia Testnet',
    rpcUrl: 'https://sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID', // Replace with your Infura Project ID
    blockExplorer: 'https://sepolia.etherscan.io',
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 137,
    name: 'Polygon Mainnet',
    rpcUrl: 'https://polygon-rpc.com',
    blockExplorer: 'https://polygonscan.com',
    nativeCurrency: {
      name: 'MATIC',
      symbol: 'MATIC',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 80001,
    name: 'Polygon Mumbai Testnet',
    rpcUrl: 'https://rpc-mumbai.maticvigil.com',
    blockExplorer: 'https://mumbai.polygonscan.com',
    nativeCurrency: {
      name: 'MATIC',
      symbol: 'MATIC',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 56,
    name: 'BNB Smart Chain Mainnet',
    rpcUrl: 'https://bsc-dataseed.binance.org',
    blockExplorer: 'https://bscscan.com',
    nativeCurrency: {
      name: 'BNB',
      symbol: 'BNB',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 97,
    name: 'BNB Smart Chain Testnet',
    rpcUrl: 'https://data-seed-prebsc-1-s1.binance.org:8545',
    blockExplorer: 'https://testnet.bscscan.com',
    nativeCurrency: {
      name: 'BNB',
      symbol: 'BNB',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 42161,
    name: 'Arbitrum One',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    blockExplorer: 'https://arbiscan.io',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 421613,
    name: 'Arbitrum Goerli Testnet',
    rpcUrl: 'https://goerli-rollup.arbitrum.io/rpc',
    blockExplorer: 'https://goerli.arbiscan.io',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 10,
    name: 'Optimism Mainnet',
    rpcUrl: 'https://mainnet.optimism.io',
    blockExplorer: 'https://optimistic.etherscan.io',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 420,
    name: 'Optimism Goerli Testnet',
    rpcUrl: 'https://goerli.optimism.io',
    blockExplorer: 'https://goerli-optimism.etherscan.io',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 43114,
    name: 'Avalanche C-Chain',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    blockExplorer: 'https://snowtrace.io',
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
  {
    chainId: 43113,
    name: 'Avalanche Fuji Testnet',
    rpcUrl: 'https://api.avax-test.network/ext/bc/C/rpc',
    blockExplorer: 'https://testnet.snowtrace.io',
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    contracts: {
      libertyToken: '0x...',
      creatorRegistry: '0x...',
      contentRegistry: '0x...',
      revenueSplitter: '0x...',
      subscriptionManager: '0x...',
      nftAccess: '0x...',
      libertyDAO: '0x...',
    },
  },
];